name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        cd oa_server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Linter
      run: |
        cd oa_server
        pylint -d C0114,C0115,C0116,W0611 --load-plugins pylint_django devices oa_server time_series || pylint-exit -efail -rfail -cfail $?
    - name: Run Unit Tests
      run: |
        cd oa_server
        python manage.py test
    - name: Coverage
      run: |
        cd oa_server
        python -m coverage run --source='.' manage.py test oa_server
        python -m coverage html
    - name: Upload Coverage
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: oa_server/htmlcov
